version: '3'
services:
  server:
    build:
      context: .
      dockerfile: docker/server.dockerfile
    container_name: server
    network_mode: host
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: docker/client.dockerfile
    container_name: client
    network_mode: host
    restart: unless-stopped
    depends_on:
      - server
